sudo: required
language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
addons:
  sonarcloud:
    organization: "tuxjsql"
    token:
      secure: "T5ZgEB+s/h1ylUKAImzrNSyKavHiP85EUmfYsO/P6KU3d/YWvW4C4aWG+oYlfCM3vtF1+Tyy/u7jztCqBZslr2T9dGDZwU35PxHZhx2OZ16fDRv1Cs4OTNt96f+ZsTpcNns7R/hQcmh39+2YfiQ0l9yT7OTPC+ZO1g7TZF0OeTHnkrUYeLNzviW8HnQUNRIMUpwoUWxY27VQMxEgosZBSZw9IuoS8VET3K6M1M6f2CxdFbwf1XWPGYfhpSSA5iXr0WQjG7NLQN/vSKqz6NGebhy/dTO/V09lUtDULtM6caMMv+C3wfa635dia/gEA7VXAgKU+VFzmh4+aGfGZhM854BZ/GXEdwjyl0mmaqzLi1UbY4CmzIQRZIBX9RtMwa0Yp9/YGlYhBOp9oF5+VBkoYzMLg+7ZNdhi9L1J2kFYkgXrPEkjId9y0O3dUwmvgS5uijQ1s+zpf5yh8ufffJ/vzZC8gXGPVhT85uog5t+IrgDJjnWJpTn9AmWb2NjOhlFC3COd7ATuxpBASbWIeKcnIR77qYLV3fBh2weauwlF7+29OgHK2nX/WZey6ePIZBuQvKav/r82+fK/2fy4E7TmtM7XaE4tKNfuMcFL80yYSpAYMrX1ktlPQ97ySce+dBdvnF/JwJBDG5hh5jVnFRJrpAiztXP5gauhzB6dHXJnlhc="


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar