sudo: required
language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
addons:
  sonarcloud:
    organization: "tuxjsql"
    token:
      secure: "X3E112PxDwMzI7VwEAhPyfXahCpgPyoBcSvY+EHHDpjQgYb71eZdJFqK9cE68UAPlb7Mfi7YpDoVELDnbjV5leG+B8+yUgDvgkXIuKgyKO0wZ3Vefm2I1yBlcwT9CUha+RJMNNeMi8pqlBIdehKVv1J5lQx2neLwAAkUe2LipafOEurlZa8+exnN3FmMUUu32p7nTJUn8WG8W/9eLKc9vmIrgEZ9SPSCMb5MG0vKdZHpYa/JQLt9GpyQYAKSTJWFdDx+BaSuyO4mvJhWOle2iD+g75d5jBTKw/3C5d9ooqWcUV4Z73fwKX/YZ01zxzohDzVVimS9nh6ZBNB9jSOgDnW/0INu7NK9VmzaDothTzwpsnygfm3sh4g81zEf/Zd+/ZEJzqlaeshGYc2PDsmo7bk0yTZgczD+KjwA0fQf8Q1nmMGZlSF1ODM1/QRr0F9FCuyR30Y/TII0e6s4gJt2UsXj9ve6Z4e9jnXnWBN/THiRueEi4a1LKdo1ng/XyhMMwzRf+M7eTMv9xOTiX5bHDMNpZKC1QvuwuN0/tCRdorfGcqXX3g0nFCej1yDx59lSnRJKd3KasP/bQtEF1RoAe9E4kIrl+G0BVkvyjwEgufbc8RYG6gi9a0HZDBO1FIP77tVUMfi6o29UK3i4DjhseLV2fuXUBr/UBxPozsiaBVE="


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar