sudo: false
language: java
install: true
jdk:
  - openjdk8
  - openjdk9
  - openjdk12
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn sonar:sonar \ Dsonar.projectKey=tuxjsql_tuxjsql \ Dsonar.organization=tuxjsql \ Dsonar.host.url=https://sonarcloud.io \ Dsonar.login=$SONAR_LOGIN
