sudo: false
language: java
install: true
jdk:
  - openjdk8
  - openjdk9
  - openjdk12
addons:
  sonarcloud:
    organization: "tuxjsql"
    token:
      secure: "HfWR7ZT1HunGy2dzWu+uE2uC1/pGgRAEDYdMIrv7ODFLT4ypDAw4ZeSRz/gmBOWoGSO2rhChWu/8MMmiWPUF9ru5Q8V3n8a0FBAgLiltM2xEMrgoKhh8D9GzDw98kGLgjjnggZZH2DMRImPN6kV6/aX9amw7doI+nZ6IJTGeF5Tyhx6jEb/FD6S2PRhLVIcBjlougW3Twvfi3GmjmT9WDJJOrjfW0p+QxXUYaRhkURLI+flHKZQ4z36QJi1KOnDZpp3pta9nnmVF5Ypaiavec5ZQB6TKIqutmGn1/6Ifa9D52rfU7P29gurYAwYDj0FjmSCnswPP6Hq/54JYmF8RCbdlknSZTYUTNRPqnl6ghlQJRi8KLwwQX989Cdh2S/frH0j1J6SYTjW0grN8BXQBN5CNUGlui7pMlzG+EN+dEXMa52malqSVw1zrz/Q+w9gR//G28ZHxDuZ4sVFDNylyD5cGdiD2f10JZnhKSdM467tsUooUVcGW/55cflf07yVadLygWDEW4g7SudL2cPHPvpReDGN5yfPEnJr+XoxvNND34f7D2cyVs2Jfo4uhi0OHZfWA2DN7c1DHxrJaUWsnX/Ae8nunuueBlexuPvVhx4PAa6DvlFsZYbemlkBjHQvH78bLoCvEJtVtrE6QAfBeqOy45riCJ4SbC0X6v8jO01o="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'